stock_symbols = [

    # SP500

    'MMM', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP',
    'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALXN', 'ALGN',
    'ALLE', 'AGN', 'ADS', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR',
    'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN',
    'APH', 'ADI', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'AIV', 'AAPL', 'AMAT', 'APTV',
    'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY',
    'BKR', 'BLL', 'BAC', 'BK', 'BAX', 'BDX', 'BBY', 'BIIB', 'BLK', 'BA',
    'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'CHRW', 'COG', 'CDNS',
    'CPB', 'COF', 'CPRI', 'CAH', 'KMX', 'CCL', 'CARR', 'CAT', 'CBOE', 'CBRE', 'CDW',
    'CE', 'CNC', 'CNP', 'CTL', 'CERN', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 
    'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 
    'CXO', 'COP', 'ED', 'STZ', 'COO', 'CPRT', 'GLW', 'CTVA', 'COST', 'COTY', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 
    'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'FANG', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DG', 
    'DLTR', 'D', 'DOV', 'DOW', 'DTE', 'DUK', 'DRE', 'DD', 'DXC', 'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 
    'EW', 'EA', 'EMR', 'ETR', 'EOG', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'EVRG', 'ES', 'RE', 'EXC', 'EXPE', 
    'EXPD', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FE', 'FRC', 'FISV', 'FLT', 
    'FLIR', 'FLS', 'FMC', 'F', 'FTNT', 'FTV', 'FBHS', 'FOXA', 'FOX', 'BEN', 'FCX', 'GPS', 'GRMN', 'IT', 
    'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'GWW', 'HRB', 'HAL', 'HBI', 'HOG', 'HIG', 
    'HAS', 'HCA', 'PEAK', 'HP', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HFC', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 
    'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'INFO', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 
    'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IPGP', 'IQV', 'IRM', 'JKHY', 'J', 'JBHT', 'SJM', 'JNJ', 'JCI', 
    'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KSS', 'KHC', 'KR', 'LB', 'LHX', 
    'LH', 'LRCX', 'LW', 'LVS', 'LEG', 'LDOS', 'LEN', 'LLY', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 
    'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MKC', 'MXIM', 'MCD', 'MCK', 'MDT', 
    'MRK', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MNST', 'MCO', 'MS', 'MOS', 
    'MSI', 'MSCI', 'MYL', 'NDAQ', 'NOV', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 
    'NBL', 'JWN', 'NSC', 'NTRS', 'NOC', 'NLOK', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'ORLY', 'OXY', 'ODFL', 'OMC', 
    'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI', 'PRGO', 'PFE', 
    'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 
    'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 
    'ROP', 'ROST', 'RCL', 'SPGI', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SLG', 'SNA', 
    'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STE', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 
    'TGT', 'TEL', 'FTI', 'TFX', 'TXN', 'TXT', 'TMO', 'TIF', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TFC', 'TWTR', 
    'TSN', 'UDR', 'ULTA', 'USB', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UHS', 'UNM', 'VFC', 'VLO', 'VAR', 
    'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VIAC', 'V', 'VNO', 'VMC', 'WRB', 'WAB', 'WMT', 'WBA', 'DIS', 'WM', 'WAT', 
    'WEC', 'WFC', 'WELL', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WYNN', 'XEL', 'XRX', 'XLNX', 'XYL', 
    'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS',
    
    
    # NASDAQ 100

    "ATVI", "ADBE", "AMD", "ALXN", "ALGN", "GOOGL", "GOOG", "AMZN", "AMGN", "ADI", "ANSS", "AAPL", "AMAT", "ASML",
    "ADSK", "ADP", "BIDU", "BIIB", "BMRN", "BKNG", "AVGO", "CDNS", "CDW", "CERN", "CHTR", "CHKP", "CTAS", "CSCO", 
    "CTXS", "CTSH", "CMCSA", "CPRT", "COST", "CSX", "DXCM", "DOCU", "DLTR", "EBAY", "EA", "EXC", "EXPE", "FB", 
    "FAST", "FISV", "FOXA", "FOX", "GILD", "IDXX", "ILMN", "INCY", "INTC", "INTU", "ISRG", "JD", "KLAC", "KHC", 
    "LRCX", "LBTYA", "LBTYK", "LULU", "MAR", "MXIM", "MELI", "MCHP", "MU", "MSFT", "MRNA", "MondelēMDLZ", "MNST", 
    "NTAP", "NTES", "NFLX", "NVDA", "NXPI", "O'ORLY", "PCAR", "PAYX", "PYPL", "PEP", "QCOM", "REGN", "ROST", "SGEN", 
    "SIRI", "SWKS", "SPLK", "SBUX", "SNPS", "T-TMUS", "Take-TTWO", "TSLA", "TXN", "TCOM", "ULTA", "VRSN", "VRSK", 
    "VRTX", "WBA", "WDAY", "WDC", "XEL", "XLNX", "ZM",
    
    
    # RUSSELL 2000

    "TWOU", "MMM", "ABT", "ABBV", "ABMD", "ACHC", "ACN", "ATVI", "AYI", "ADNT", "ADBE", 
    "ADT", "AAP", "AMD", "ACM", "AES", "AMG", "AFL", "AGCO", "A", "AGIO", 
    "AGNC", "AL", "APD", "AKAM", "ALK", "ALB", "AA", "ARE", "ALXN", "ALGN", 
    "ALKS", "Y", "ALLE", "AGN", "ADS", "LNT", "ALSN", "ALL", "ALLY", "ALNY", 
    "GOOGL", "GOOG", "MO", "AMZN", "AMCX", "DOX", "UHAL", "AEE", "AAL", "ACC", 
    "AEP", "AXP", "AFG", "AMH", "AIG", "ANAT", "AMT", "AWK", "AMP", "ABC", 
    "AME", "AMGN", "APH", "ADI", "NLY", "ANSS", "AR", "ANTM", "AON", "APA", 
    "AIV", "APY", "APLE", "AAPL", "AMAT", "ATR", "APTV", "WTR", "ARMK", "ACGL", 
    "ADM", "ARNC", "ARD", "ANET", "AWI", "ARW", "ASH", "AZPN", "ASB", "AIZ", 
    "AGO", "T", "ATH", "TEAM", "ATO", "ADSK", "ADP", "AN", "AZO", "AVB", 
    "AGR", "AVY", "AVT", "EQH", "AXTA", "AXS", "BKR", "BLL", "BAC", "BOH", 
    "BK", "OZK", "BKU", "BAX", "BDX", "WRB", "BRK.B", "BERY", "BBY", "BYND", 
    "BGCP", "BIIB", "BMRN", "BIO", "TECH", "BKI", "BLK", "HRB", "BLUE", "BA", 
    "BOKF", "BKNG", "BAH", "BWA", "BSX", "BDN", "BFAM", "BHF", "BMY", "BRX", 
    "AVGO", "BR", "BPYU", "BRO", "Brown–BFA", "Brown–BFB", "BRKR", "BC", "BG", "BURL", 
    "BWXT", "CHRW", "CABO", "CBT", "COG", "CACI", "CDNS", "CZR", "CPT", "CPB", 
    "CMD", "COF", "CAH", "CSL", "KMX", "CCL", "CRI", "CASY", "CTLT", "CAT", 
    "CBOE", "CBRE", "CBS", "CDK", "CDW", "CE", "CELG", "CNC", "CDEV", "CNP", 
    "CTL", "CDAY", "BXP", "CF", "CRL", "CHTR", "CHE", "LNG", "CHK", "CVX", 
    "CIM", "CMG", "CHH", "CB", "CHD", "CI", "XEC", "CINF", "CNK", "CTAS", 
    "CSCO", "CIT", "C", "CFG", "CTXS", "CLH", "CLX", "CME", "CMS", "CNA", 
    "CNX", "KO", "CGNX", "CTSH", "COHR", "CFX", "CL", "CLNY", "CXP", "COLM", 
    "CMCSA", "CMA", "CBSH", "COMM", "CAG", "CXO", "CNDT", "COP", "ED", "STZ", 
    "CERN", "CPA", "CPRT", "CLGX", "COR", "GLW", "OFC", "CSGP", "COST", "COTY", 
    "CR", "CACC", "CCI", "CCK", "CSX", "CUBE", "CFR", "CMI", "CW", "CVS", 
    "CY", "CONE", "DHI", "DHR", "DRI", "DVA", "SITC", "DE", "DELL", "DAL", 
    "XRAY", "DVN", "DXCM", "FANG", "DKS", "DLR", "DFS", "DISCA", "DISCK", "DISH", 
    "DIS", "DHC", "DOCU", "DLB", "DG", "DLTR", "D", "DPZ", "CLR", "COO", 
    "DEI", "DOV", "DD", "DPS", "DTE", "DUK", "DRE", "DNB", "DNKN", "DXC", 
    "ETFC", "EXP", "EWBC", "EMN", "ETN", "EV", "EBAY", "SATS", "ECL", "EIX", 
    "EW", "EA", "EMR", "ESRT", "EHC", "EGN", "ENR", "ETR", "EVHC", "EOG", 
    "EPAM", "EPR", "EQT", "EFX", "EQIX", "EQC", "ELS", "EQR", "ERIE", "ESS", 
    "EL", "EEFT", "EVBG", "EVR", "RE", "EVRG", "ES", "UFS", "DCI", "EXPE", 
    "EXPD", "STAY", "EXR", "XOG", "XOM", "FFIV", "FB", "FDS", "FICO", "FAST", 
    "FRT", "FDX", "FIS", "FITB", "FEYE", "FAF", "FCNCA", "FDC", "FHB", "FHN", 
    "FRC", "FSLR", "FE", "FISV", "FLT", "FLIR", "FND", "FLO", "FLS", "FLR", 
    "FMC", "FNB", "FNF", "FL", "F", "FTNT", "FTV", "FBHS", "FOXA", "FOX", 
    "BEN", "FCX", "AJG", "GLPI", "GPS", "EXAS", "EXEL", "EXC", "GTES", "GLIBA", 
    "GD", "GE", "GIS", "GM", "GWR", "G", "GNTX", "GPC", "GILD", "GPN", 
    "GL", "GDDY", "GS", "GT", "GRA", "GGG", "EAF", "GHC", "GWW", "LOPE", 
    "GPK", "GRUB", "GWRE", "HAIN", "HAL", "HBI", "THG", "HOG", "HIG", "HAS", 
    "HE", "HCA", "HDS", "HTA", "PEAK", "HEI.A", "HEI", "HP", "JKHY", "HLF", 
    "HSY", "HES", "GDI", "GRMN", "IT", "HGV", "HLT", "HFC", "HOLX", "HD", 
    "HON", "HRL", "HST", "HHC", "HPQ", "HUBB", "HPP", "HUM", "HBAN", "HII", 
    "HUN", "H", "IAC", "ICUI", "IEX", "IDXX", "INFO", "ITW", "ILMN", "INCY", 
    "IR", "INGR", "PODD", "IART", "INTC", "IBKR", "ICE", "IGT", "IP", "IPG", 
    "IBM", "IFF", "INTU", "ISRG", "IVZ", "INVH", "IONS", "IPGP", "IQV", "HPE", 
    "HXL", "HIW", "HRC", "JAZZ", "JBHT", "JBGS", "JEF", "JBLU", "JNJ", "JCI", 
    "JLL", "JPM", "JNPR", "KSU", "KAR", "K", "KEY", "KEYS", "KRC", "KMB", 
    "KIM", "KMI", "KEX", "KLAC", "KNX", "KSS", "KOS", "KR", "LB", "LHX", 
    "LH", "LRCX", "LAMR", "LW", "LSTR", "LVS", "LAZ", "LEA", "LM", "LEG", 
    "LDOS", "LEN", "LEN.B", "LII", "LBRDA", "LBRDK", "FWONA", "IRM", "ITT", "JBL", 
    "JEC", "LLY", "LECO", "LNC", "LGF.A", "LGF.B", "LFUS", "LYV", "LKQ", "LMT", 
    "L", "LOGM", "LOW", "LPLA", "LULU", "LYFT", "LYB", "MTB", "MAC", "MIC", 
    "M", "MSG", "MANH", "MAN", "MRO", "MPC", "MKL", "MKTX", "MAR", "MMC", 
    "MLM", "MRVL", "MAS", "MASI", "MA", "MTCH", "MAT", "MXIM", "MKC", "MCD", 
    "MCK", "MDU", "MPW", "MD", "MDT", "MRK", "FWONK", "LPT", "LSXMA", "LSXMK", 
    "LSI", "CPRI", "MIK", "MCHP", "MU", "MSFT", "MAA", "MIDD", "MKSI", "MHK", 
    "MOH", "TAP", "MDLZ", "MPWR", "MNST", "MCO", "MS", "MORN", "MOS", "MSI", 
    "MSM", "MSCI", "MUR", "MYL", "NBR", "NDAQ", "NFG", "NATI", "NOV", "NNN", 
    "NAVI", "NCR", "NKTR", "NTAP", "NFLX", "NBIX", "NRZ", "NYCB", "NWL", "NEU", 
    "NEM", "NWSA", "NWS", "MCY", "MET", "MTD", "MFA", "MGM", "JWN", "NSC", 
    "NTRS", "NOC", "NLOK", "NCLH", "NRG", "NUS", "NUAN", "NUE", "NTNX", "NVT", 
    "NVDA", "NVR", "NXPI", "ORLY", "OXY", "OGE", "OKTA", "ODFL", "ORI", "OLN", 
    "OHI", "OMC", "ON", "OMF", "OKE", "ORCL", "OSK", "OUT", "OC", "OI", 
    "PCAR", "PKG", "PACW", "PANW", "PGRE", "PK", "PH", "PE", "PTEN", "PAYX", 
    "PAYC", "PYPL", "NEE", "NLSN", "NKE", "NI", "NBL", "NDSN", "PEP", "PKI", 
    "PRGO", "PFE", "PCG", "PM", "PSX", "PPC", "PNFP", "PF", "PNW", "PXD", 
    "ESI", "PNC", "PII", "POOL", "BPOP", "POST", "PPG", "PPL", "PRAH", "PINC", 
    "TROW", "PFG", "PG", "PGR", "PLD", "PFPT", "PB", "PRU", "PTC", "PSA", 
    "PEG", "PHM", "PSTG", "PVH", "QGEN", "QRVO", "QCOM", "PWR", "PBF", "PEGA", 
    "PAG", "PNR", "PEN", "PBCT", "RLGY", "RP", "O", "RBC", "REG", "REGN", 
    "RF", "RGA", "RS", "RNR", "RSG", "RMD", "RPAI", "RNG", "RHI", "ROK", 
    "ROL", "ROP", "ROST", "RCL", "RGLD", "RES", "RPM", "RSPP", "R", "SPGI", 
    "SABR", "SAGE", "CRM", "SC", "SRPT", "SBAC", "HSIC", "SLB", "SNDR", "SCHW", 
    "SMG", "SEB", "SEE", "DGX", "QRTEA", "RL", "RRC", "RJF", "RYN", "RTN", 
    "NOW", "SVC", "SHW", "SBNY", "SLGN", "SPG", "SIRI", "SIX", "SKX", "SWKS", 
    "SLG", "SLM", "SM", "AOS", "SJM", "SNA", "SON", "SO", "SCCO", "LUV", 
    "SPB", "SPR", "SRC", "SPLK", "S", "SFM", "SQ", "SSNC", "SWK", "SBUX", 
    "STWD", "STT", "STLD", "SRCL", "STE", "STL", "STOR", "SYK", "SUI", "STI", 
    "SIVB", "SWCH", "SGEN", "SEIC", "SRE", "ST", "SCI", "SERV", "TPR", "TRGP", 
    "TGT", "TCO", "TCF", "AMTD", "TDY", "TFX", "TDS", "TPX", "TDC", "TER", 
    "TEX", "TSRO", "TSLA", "TCBI", "TXN", "TXT", "TFSL", "CC", "KHC", "WEN", 
    "TMO", "THO", "TIF", "TKR", "TJX", "TOL", "TTC", "TSCO", "TDG", "RIG", 
    "TRU", "TRV", "THS", "TPCO", "TRMB", 
    "TWOU", "MMM", "ABT", "ABBV", "ABMD", "ACHC", "ACN", "ATVI", "AYI", "ADNT", "ADBE", 
    "ADT", "AAP", "AMD", "ACM", "AES", "AMG", "AFL", "AGCO", "A", "AGIO", 
    "AGNC", "AL", "APD", "AKAM", "ALK", "ALB", "AA", "ARE", "ALXN", "ALGN", 
    "ALKS", "Y", "ALLE", "AGN", "ADS", "LNT", "ALSN", "ALL", "ALLY", "ALNY", 
    "GOOGL", "GOOG", "MO", "AMZN", "AMCX", "DOX", "UHAL", "AEE", "AAL", "ACC", 
    "AEP", "AXP", "AFG", "AMH", "AIG", "ANAT", "AMT", "AWK", "AMP", "ABC", 
    "AME", "AMGN", "APH", "ADI", "NLY", "ANSS", "AR", "ANTM", "AON", "APA", 
    "AIV", "APY", "APLE", "AAPL", "AMAT", "ATR", "APTV", "WTR", "ARMK", "ACGL", 
    "ADM", "ARNC", "ARD", "ANET", "AWI", "ARW", "ASH", "AZPN", "ASB", "AIZ", 
    "AGO", "T", "ATH", "TEAM", "ATO", "ADSK", "ADP", "AN", "AZO", "AVB", 
    "AGR", "AVY", "AVT", "EQH", "AXTA", "AXS", "BKR", "BLL", "BAC", "BOH", 
    "BK", "OZK", "BKU", "BAX", "BDX", "WRB", "BRK.B", "BERY", "BBY", "BYND", 
    "BGCP", "BIIB", "BMRN", "BIO", "TECH", "BKI", "BLK", "HRB", "BLUE", "BA", 
    "BOKF", "BKNG", "BAH", "BWA", "BSX", "BDN", "BFAM", "BHF", "BMY", "BRX", 
    "AVGO", "BR", "BPYU", "BRO", "Brown–BFA", "Brown–BFB", "BRKR", "BC", "BG", "BURL", 
    "BWXT", "CHRW", "CABO", "CBT", "COG", "CACI", "CDNS", "CZR", "CPT", "CPB", 
    "CMD", "COF", "CAH", "CSL", "KMX", "CCL", "CRI", "CASY", "CTLT", "CAT", 
    "CBOE", "CBRE", "CBS", "CDK", "CDW", "CE", "CELG", "CNC", "CDEV", "CNP", 
    "CTL", "CDAY", "BXP", "CF", "CRL", "CHTR", "CHE", "LNG", "CHK", "CVX", 
    "CIM", "CMG", "CHH", "CB", "CHD", "CI", "XEC", "CINF", "CNK", "CTAS", 
    "CSCO", "CIT", "C", "CFG", "CTXS", "CLH", "CLX", "CME", "CMS", "CNA", 
    "CNX", "KO", "CGNX", "CTSH", "COHR", "CFX", "CL", "CLNY", "CXP", "COLM", 
    "CMCSA", "CMA", "CBSH", "COMM", "CAG", "CXO", "CNDT", "COP", "ED", "STZ", 
    "CERN", "CPA", "CPRT", "CLGX", "COR", "GLW", "OFC", "CSGP", "COST", "COTY", 
    "CR", "CACC", "CCI", "CCK", "CSX", "CUBE", "CFR", "CMI", "CW", "CVS", 
    "CY", "CONE", "DHI", "DHR", "DRI", "DVA", "SITC", "DE", "DELL", "DAL", 
    "XRAY", "DVN", "DXCM", "FANG", "DKS", "DLR", "DFS", "DISCA", "DISCK", "DISH", 
    "DIS", "DHC", "DOCU", "DLB", "DG", "DLTR", "D", "DPZ", "CLR", "COO", 
    "DEI", "DOV", "DD", "DPS", "DTE", "DUK", "DRE", "DNB", "DNKN", "DXC", 
    "ETFC", "EXP", "EWBC", "EMN", "ETN", "EV", "EBAY", "SATS", "ECL", "EIX", 
    "EW", "EA", "EMR", "ESRT", "EHC", "EGN", "ENR", "ETR", "EVHC", "EOG", 
    "EPAM", "EPR", "EQT", "EFX", "EQIX", "EQC", "ELS", "EQR", "ERIE", "ESS", 
    "EL", "EEFT", "EVBG", "EVR", "RE", "EVRG", "ES", "UFS", "DCI", "EXPE", 
    "EXPD", "STAY", "EXR", "XOG", "XOM", "FFIV", "FB", "FDS", "FICO", "FAST", 
    "FRT", "FDX", "FIS", "FITB", "FEYE", "FAF", "FCNCA", "FDC", "FHB", "FHN", 
    "FRC", "FSLR", "FE", "FISV", "FLT", "FLIR", "FND", "FLO", "FLS", "FLR", 
    "FMC", "FNB", "FNF", "FL", "F", "FTNT", "FTV", "FBHS", "FOXA", "FOX", 
    "BEN", "FCX", "AJG", "GLPI", "GPS", "EXAS", "EXEL", "EXC", "GTES", "GLIBA", 
    "GD", "GE", "GIS", "GM", "GWR", "G", "GNTX", "GPC", "GILD", "GPN", 
    "GL", "GDDY", "GS", "GT", "GRA", "GGG", "EAF", "GHC", "GWW", "LOPE", 
    "GPK", "GRUB", "GWRE", "HAIN", "HAL", "HBI", "THG", "HOG", "HIG", "HAS", 
    "HE", "HCA", "HDS", "HTA", "PEAK", "HEI.A", "HEI", "HP", "JKHY", "HLF", 
    "HSY", "HES", "GDI", "GRMN", "IT", "HGV", "HLT", "HFC", "HOLX", "HD", 
    "HON", "HRL", "HST", "HHC", "HPQ", "HUBB", "HPP", "HUM", "HBAN", "HII", 
    "HUN", "H", "IAC", "ICUI", "IEX", "IDXX", "INFO", "ITW", "ILMN", "INCY", 
    "IR", "INGR", "PODD", "IART", "INTC", "IBKR", "ICE", "IGT", "IP", "IPG", 
    "IBM", "IFF", "INTU", "ISRG", "IVZ", "INVH", "IONS", "IPGP", "IQV", "HPE", 
    "HXL", "HIW", "HRC", "JAZZ", "JBHT", "JBGS", "JEF", "JBLU", "JNJ", "JCI", 
    "JLL", "JPM", "JNPR", "KSU", "KAR", "K", "KEY", "KEYS", "KRC", "KMB", 
    "KIM", "KMI", "KEX", "KLAC", "KNX", "KSS", "KOS", "KR", "LB", "LHX", 
    "LH", "LRCX", "LAMR", "LW", "LSTR", "LVS", "LAZ", "LEA", "LM", "LEG", 
    "LDOS", "LEN", "LEN.B", "LII", "LBRDA", "LBRDK", "FWONA", "IRM", "ITT", "JBL", 
    "JEC", "LLY", "LECO", "LNC", "LGF.A", "LGF.B", "LFUS", "LYV", "LKQ", "LMT", 
    "L", "LOGM", "LOW", "LPLA", "LULU", "LYFT", "LYB", "MTB", "MAC", "MIC", 
    "M", "MSG", "MANH", "MAN", "MRO", "MPC", "MKL", "MKTX", "MAR", "MMC", 
    "MLM", "MRVL", "MAS", "MASI", "MA", "MTCH", "MAT", "MXIM", "MKC", "MCD", 
    "MCK", "MDU", "MPW", "MD", "MDT", "MRK", "FWONK", "LPT", "LSXMA", "LSXMK", 
    "LSI", "CPRI", "MIK", "MCHP", "MU", "MSFT", "MAA", "MIDD", "MKSI", "MHK", 
    "MOH", "TAP", "MDLZ", "MPWR", "MNST", "MCO", "MS", "MORN", "MOS", "MSI", 
    "MSM", "MSCI", "MUR", "MYL", "NBR", "NDAQ", "NFG", "NATI", "NOV", "NNN", 
    "NAVI", "NCR", "NKTR", "NTAP", "NFLX", "NBIX", "NRZ", "NYCB", "NWL", "NEU", 
    "NEM", "NWSA", "NWS", "MCY", "MET", "MTD", "MFA", "MGM", "JWN", "NSC", 
    "NTRS", "NOC", "NLOK", "NCLH", "NRG", "NUS", "NUAN", "NUE", "NTNX", "NVT", 
    "NVDA", "NVR", "NXPI", "ORLY", "OXY", "OGE", "OKTA", "ODFL", "ORI", "OLN", 
    "OHI", "OMC", "ON", "OMF", "OKE", "ORCL", "OSK", "OUT", "OC", "OI", 
    "PCAR", "PKG", "PACW", "PANW", "PGRE", "PK", "PH", "PE", "PTEN", "PAYX", 
    "PAYC", "PYPL", "NEE", "NLSN", "NKE", "NI", "NBL", "NDSN", "PEP", "PKI", 
    "PRGO", "PFE", "PCG", "PM", "PSX", "PPC", "PNFP", "PF", "PNW", "PXD", 
    "ESI", "PNC", "PII", "POOL", "BPOP", "POST", "PPG", "PPL", "PRAH", "PINC", 
    "TROW", "PFG", "PG", "PGR", "PLD", "PFPT", "PB", "PRU", "PTC", "PSA", 
    "PEG", "PHM", "PSTG", "PVH", "QGEN", "QRVO", "QCOM", "PWR", "PBF", "PEGA", 
    "PAG", "PNR", "PEN", "PBCT", "RLGY", "RP", "O", "RBC", "REG", "REGN", 
    "RF", "RGA", "RS", "RNR", "RSG", "RMD", "RPAI", "RNG", "RHI", "ROK", 
    "ROL", "ROP", "ROST", "RCL", "RGLD", "RES", "RPM", "RSPP", "R", "SPGI", 
    "SABR", "SAGE", "CRM", "SC", "SRPT", "SBAC", "HSIC", "SLB", "SNDR", "SCHW", 
    "SMG", "SEB", "SEE", "DGX", "QRTEA", "RL", "RRC", "RJF", "RYN", "RTN", 
    "NOW", "SVC", "SHW", "SBNY", "SLGN", "SPG", "SIRI", "SIX", "SKX", "SWKS", 
    "SLG", "SLM", "SM", "AOS", "SJM", "SNA", "SON", "SO", "SCCO", "LUV", 
    "SPB", "SPR", "SRC", "SPLK", "S", "SFM", "SQ", "SSNC", "SWK", "SBUX", 
    "STWD", "STT", "STLD", "SRCL", "STE", "STL", "STOR", "SYK", "SUI", "STI", 
    "SIVB", "SWCH", "SGEN", "SEIC", "SRE", "ST", "SCI", "SERV", "TPR", "TRGP", 
    "TGT", "TCO", "TCF", "AMTD", "TDY", "TFX", "TDS", "TPX", "TDC", "TER", 
    "TEX", "TSRO", "TSLA", "TCBI", "TXN", "TXT", "TFSL", "CC", "KHC", "WEN", 
    "TMO", "THO", "TIF", "TKR", "TJX", "TOL", "TTC", "TSCO", "TDG", "RIG", 
    "TRU", "TRV", "THS", "TPCO", "TRMB", "TRN", "TRIP", "SYF", "SNPS", "SNV", 
    "SYY", "DATA", "TTWO", "TMUS", "TFC", "UBER", "UGI", "ULTA", "ULTI", "UMPQ", 
    "UAA", "UA", "UNP", "UAL", "UPS", "URI", "USM", "X", "UTX", "UTHR", 
    "UNH", "UNIT", "UNVR", "OLED", "UHS", "UNM", "URBN", "USB", "USFD", "VFC", 
    "MTN", "VLO", "VMI", "VVV", "VAR", "VVC", "VEEV", "VTR", "VER", "VRSN", 
    "VRSK", "VZ", "VSM", "VRTX", "VIAC", "TWLO", "TWTR", "TWO", "TYL", "TSN", 
    "USG", "UI", "UDR", "VMC", "WPC", "WBC", "WAB", "WBA", "WMT", "WM", 
    "WAT", "WSO", "W", "WFTLF", "WBS", "WEC", "WRI", "WBT", "WCG", "WFC", 
    "WELL", "WCC", "WST", "WAL", "WDC", "WU", "WLK", "WRK", "WEX", "WY", 
    "WHR", "WTM", "WLL", "JW.A", "WMB", "WSM", "WLTW", "WTFC", "WDAY", "WP", 
    "WPX", "WYND", "WH", "VIAB", "VICI", "VIRT", "V", "VC", "VST", "VMW", 
    "VNO", "VOYA", "ZAYO", "ZBRA", "ZEN", "ZG", "Z", "ZBH", "ZION", "ZTS", "TRN", "TRIP", "SYF", "SNPS", "SNV", 
    "SYY", "DATA", "TTWO", "TMUS", "TFC", "UBER", "UGI", "ULTA", "ULTI", "UMPQ", 
    "UAA", "UA", "UNP", "UAL", "UPS", "URI", "USM", "X", "UTX", "UTHR", 
    "UNH", "UNIT", "UNVR", "OLED", "UHS", "UNM", "URBN", "USB", "USFD", "VFC", 
    "MTN", "VLO", "VMI", "VVV", "VAR", "VVC", "VEEV", "VTR", "VER", "VRSN", 
    "VRSK", "VZ", "VSM", "VRTX", "VIAC", "TWLO", "TWTR", "TWO", "TYL", "TSN", 
    "USG", "UI", "UDR", "VMC", "WPC", "WBC", "WAB", "WBA", "WMT", "WM", 
    "WAT", "WSO", "W", "WFTLF", "WBS", "WEC", "WRI", "WBT", "WCG", "WFC", 
    "WELL", "WCC", "WST", "WAL", "WDC", "WU", "WLK", "WRK", "WEX", "WY", 
    "WHR", "WTM", "WLL", "JW.A", "WMB", "WSM", "WLTW", "WTFC", "WDAY", "WP", 
    "WPX", "WYND", "WH", "VIAB", "VICI", "VIRT", "V", "VC", "VST", "VMW", 
    "VNO", "VOYA", "ZAYO", "ZBRA", "ZEN", "ZG", "Z", "ZBH", "ZION", "ZTS", 



    
    ]

